volumes:
  chop_geo_local_postgres_data: {}
  chop_geo_local_postgres_data_backups: {}
  chop_geo_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: chop_geo_local_django
    container_name: chop_geo_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: chop_geo_production_postgres
    container_name: chop_geo_local_postgres
    volumes:
      - chop_geo_local_postgres_data:/var/lib/postgresql/data
      - chop_geo_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:6
    container_name: chop_geo_local_redis

    volumes:
      - chop_geo_local_redis_data:/data


  celeryworker:
    <<: *django
    image: chop_geo_local_celeryworker
    container_name: chop_geo_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: chop_geo_local_celerybeat
    container_name: chop_geo_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
