volumes:
  clinic_production_postgres_data: {}
  clinic_production_postgres_data_backups: {}
  clinic_production_redis_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: clinic_production_django
    volumes:
      - /var/www/geo.leetcode.uz/media:/app/media
      - /var/www/geo.leetcode.uz/static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "9095:5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: clinic_production_postgres
    volumes:
      - clinic_production_postgres_data:/var/lib/postgresql/data
      - clinic_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6
    volumes:
      - clinic_production_redis_data:/data

  celeryworker:
    <<: *django
    image: clinic_production_celeryworker
    command: /start-celeryworker
    ports: [ ]

  celerybeat:
    <<: *django
    image: clinic_production_celerybeat
    command: /start-celerybeat
    ports: [ ]

